//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageProcessing.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EdgeDetection")]
        public string ImageTypeSelectName {
            get {
                return ((string)(this["ImageTypeSelectName"]));
            }
            set {
                this["ImageTypeSelectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ImageTypeEdgeId
        {
            get {
                return ((int)(this["ImageTypeEdgeId"]));
            }
            set {
                this["ImageTypeEdgeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EdgeDetection")]
        public string ImageTypeEdgeName
        {
            get {
                return ((string)(this["ImageTypeEdgeName"]));
            }
            set {
                this["ImageTypeEdgeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ImageTypeGrayScaleId
        {
            get {
                return ((int)(this["ImageTypeGrayScaleId"]));
            }
            set {
                this["ImageTypeGrayScaleId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GrayScale")]
        public string ImageTypeGrayScaleName
        {
            get {
                return ((string)(this["ImageTypeGrayScaleName"]));
            }
            set {
                this["ImageTypeGrayScaleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ImageTypeBinarizationId
        {
            get {
                return ((int)(this["ImageTypeBinarizationId"]));
            }
            set {
                this["ImageTypeBinarizationId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Binarization")]
        public string ImageTypeBinarizationName
        {
            get {
                return ((string)(this["ImageTypeBinarizationName"]));
            }
            set {
                this["ImageTypeBinarizationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ImageTypeGrayScale2DiffId
        {
            get {
                return ((int)(this["ImageTypeGrayScale2DiffId"]));
            }
            set {
                this["ImageTypeGrayScale2DiffId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GrayScale 2Diff")]
        public string ImageTypeGrayScale2DiffName
        {
            get {
                return ((string)(this["ImageTypeGrayScale2DiffName"]));
            }
            set {
                this["ImageTypeGrayScale2DiffName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ImageTypeColorReversalId
        {
            get {
                return ((int)(this["ImageTypeColorReversalId"]));
            }
            set {
                this["ImageTypeColorReversalId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ColorReversal")]
        public string ImageTypeColorReversalName
        {
            get {
                return ((string)(this["ImageTypeColorReversalName"]));
            }
            set {
                this["ImageTypeColorReversalName"] = value;
            }
        }
    }
}
